{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # base64 encoded values
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  database: {{ .Values.mysql.auth.database | b64enc | quote }}
  user: {{ .Values.mysql.auth.username | b64enc | quote }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}