{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
        {{- if .Values.resources.mysql }}
        resources:
          {{- toYaml .Values.resources.mysql | nindent 10 }}
        {{- end }}
        {{- if .Values.mysql.persistence.enabled }}
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        {{- end }}
      {{- if .Values.mysql.persistence.enabled }}
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
{{- end }}